server:
  port: 3333
project:
  host: 127.0.0.1

spring:
  application:
    name: serverC
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zs_dev?characterEncoding=utf-8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true     #覆盖相同名称的bean
  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/*.xml